/**
 * Comprehensive Psychiatry Training Data
 * Based on three gold-standard psychiatry references:
 * 1. Fish's Clinical Psychopathology (5th edition, 2024)
 * 2. New Oxford Textbook of Psychiatry (3rd edition, 2020)
 * 3. Textbook of Postgraduate Psychiatry (3rd edition, 2018)
 */

export const psychiatryTrainingData = {
  // Fish's Clinical Psychopathology - Disorders of Perception
  perception: [
    {
      question: "What are hallucinations?",
      answer: "Hallucinations are false perceptions that occur without any external stimulus. They can affect any of the five senses - hearing voices (auditory), seeing things (visual), feeling things on skin (tactile), smelling odors (olfactory), or tasting things (gustatory). Unlike illusions which are misperceptions of real stimuli, hallucinations are completely generated by the mind.",
      keywords: ["hallucination", "false perception", "hearing voices", "seeing things", "senses"],
      category: "perception"
    },
    {
      question: "What's the difference between hallucinations and pseudo-hallucinations?",
      answer: "True hallucinations are experienced as coming from outside the person's mind and are indistinguishable from real perceptions. Pseudo-hallucinations are experienced as coming from within the person's own mind - they know it's not real but still experience it vividly. Pseudo-hallucinations are often associated with stress, sleep deprivation, or certain medical conditions.",
      keywords: ["pseudo-hallucination", "true hallucination", "inside mind", "outside mind"],
      category: "perception"
    },
    {
      question: "What are illusions?",
      answer: "Illusions are misperceptions of real external stimuli. For example, seeing a shadow and thinking it's a person, or hearing wind and thinking it's voices. Unlike hallucinations, there is a real stimulus present, but it's being misinterpreted by the brain.",
      keywords: ["illusion", "misperception", "real stimulus", "misinterpreted"],
      category: "perception"
    },
    {
      question: "Why do people hear voices?",
      answer: "Auditory hallucinations (hearing voices) can occur in various conditions including schizophrenia, severe depression, bipolar disorder, PTSD, and sometimes during extreme stress or sleep deprivation. The voices can be critical, commanding, or conversational. It's important to remember that hearing voices doesn't always mean someone has a serious mental illness - context and other symptoms matter greatly.",
      keywords: ["hearing voices", "auditory hallucination", "schizophrenia", "depression", "stress"],
      category: "perception"
    }
  ],

  // Fish's Clinical Psychopathology - Disorders of Thought
  thought: [
    {
      question: "What is thought alienation?",
      answer: "Thought alienation is when people feel their thoughts are not their own. This includes thought insertion (feeling thoughts are being put into their mind by others), thought withdrawal (feeling thoughts are being taken away), and thought broadcasting (feeling others can hear or read their thoughts). These experiences are often associated with schizophrenia.",
      keywords: ["thought alienation", "thought insertion", "thought withdrawal", "thought broadcasting", "not my thoughts"],
      category: "thought"
    },
    {
      question: "What is formal thought disorder?",
      answer: "Formal thought disorder refers to disorganized thinking patterns that affect how thoughts are expressed in speech. This includes tangentiality (going off-topic), circumstantiality (excessive detail), loose associations (jumping between unrelated topics), and word salad (incoherent speech). It's different from the content of thoughts - it's about how thoughts are organized and expressed.",
      keywords: ["formal thought disorder", "disorganized thinking", "tangentiality", "loose associations", "word salad"],
      category: "thought"
    },
    {
      question: "What does it mean to have racing thoughts?",
      answer: "Racing thoughts are when thoughts come very rapidly, one after another, often making it hard to focus or sleep. This is commonly seen in mania (bipolar disorder), anxiety disorders, and sometimes during panic attacks. The person may feel like their mind is going too fast to keep up with.",
      keywords: ["racing thoughts", "rapid thoughts", "mania", "bipolar", "anxiety", "panic"],
      category: "thought"
    }
  ],

  // Fish's Clinical Psychopathology - Disorders of Self
  self: [
    {
      question: "What is depersonalization?",
      answer: "Depersonalization is feeling disconnected from yourself - like you're watching yourself from outside your body, or that your body doesn't feel real. It's like being in a dream or watching a movie of yourself. This can happen during extreme stress, anxiety, trauma, or as part of depersonalization-derealization disorder.",
      keywords: ["depersonalization", "disconnected", "watching myself", "not real", "dream"],
      category: "self"
    },
    {
      question: "What is derealization?",
      answer: "Derealization is feeling like the world around you isn't real - like you're in a movie or behind glass. Everything might look flat, distant, or artificial. It often occurs with depersonalization and can be triggered by stress, trauma, or anxiety disorders.",
      keywords: ["derealization", "world not real", "movie", "artificial", "flat"],
      category: "self"
    },
    {
      question: "Why do I sometimes feel disconnected from myself?",
      answer: "Feeling disconnected from yourself can be depersonalization, which is actually quite common during stress, anxiety, or trauma. It's your mind's way of protecting you from overwhelming emotions. Grounding techniques like focusing on your breath, naming things you can see/hear/feel, or gentle movement can help. If it's persistent or distressing, please consult a mental health professional.",
      keywords: ["disconnected", "depersonalization", "stress", "anxiety", "trauma", "grounding"],
      category: "self"
    }
  ],

  // Oxford Textbook - Major Disorders
  majorDisorders: [
    {
      question: "What's the difference between sadness and depression?",
      answer: "Normal sadness is a temporary emotional response to life events, while clinical depression (major depressive disorder) is persistent low mood lasting at least 2 weeks, along with other symptoms like loss of interest, changes in sleep/appetite, fatigue, difficulty concentrating, feelings of worthlessness, or thoughts of death. Depression significantly impacts daily functioning, while sadness doesn't typically interfere with your ability to work or maintain relationships.",
      keywords: ["sadness", "depression", "clinical depression", "persistent", "2 weeks", "functioning"],
      category: "majorDisorders"
    },
    {
      question: "What is anxiety disorder?",
      answer: "Anxiety disorders involve excessive fear or worry that's persistent and interferes with daily life. This includes generalized anxiety disorder (constant worry), panic disorder (sudden intense fear attacks), social anxiety (fear of social situations), and specific phobias. Unlike normal anxiety, these disorders cause significant distress and impairment in functioning.",
      keywords: ["anxiety disorder", "excessive worry", "panic disorder", "social anxiety", "phobia"],
      category: "majorDisorders"
    },
    {
      question: "What is bipolar disorder?",
      answer: "Bipolar disorder involves episodes of mania (elevated mood, increased energy, decreased need for sleep, racing thoughts) alternating with episodes of depression. There are different types - Bipolar I has full manic episodes, Bipolar II has hypomanic episodes (less severe than mania). The mood episodes are distinct from normal mood swings and significantly impact daily functioning.",
      keywords: ["bipolar", "mania", "hypomania", "mood episodes", "elevated mood"],
      category: "majorDisorders"
    },
    {
      question: "What is schizophrenia?",
      answer: "Schizophrenia is a serious mental disorder characterized by psychosis - losing touch with reality. Symptoms include hallucinations (hearing voices), delusions (false beliefs), disorganized thinking and speech, and negative symptoms (reduced emotional expression, motivation, social withdrawal). It typically begins in late teens to early 30s and requires ongoing treatment.",
      keywords: ["schizophrenia", "psychosis", "hallucinations", "delusions", "reality"],
      category: "majorDisorders"
    }
  ],

  // Postgraduate Textbook - Clinical Management
  clinicalManagement: [
    {
      question: "What treatments are available for mental health conditions?",
      answer: "Treatment typically involves a combination of approaches: psychotherapy (like CBT - Cognitive Behavioral Therapy), medication when appropriate, lifestyle changes (exercise, sleep, nutrition), and social support. The specific treatment depends on the condition and individual needs. Most mental health conditions are highly treatable with the right support.",
      keywords: ["treatment", "psychotherapy", "CBT", "medication", "lifestyle", "treatable"],
      category: "clinicalManagement"
    },
    {
      question: "What is CBT?",
      answer: "Cognitive Behavioral Therapy (CBT) is a type of psychotherapy that helps people identify and change negative thought patterns and behaviors. It's based on the idea that our thoughts, feelings, and behaviors are interconnected. CBT is highly effective for anxiety, depression, and many other conditions. It's usually short-term (12-20 sessions) and focuses on practical skills you can use daily.",
      keywords: ["CBT", "cognitive behavioral therapy", "thought patterns", "behaviors", "short-term"],
      category: "clinicalManagement"
    },
    {
      question: "When should I seek professional help?",
      answer: "Seek professional help if symptoms persist for more than 2 weeks, significantly interfere with daily functioning, cause distress, or if you have thoughts of self-harm. Early intervention often leads to better outcomes. Mental health professionals can provide proper assessment, diagnosis, and treatment planning.",
      keywords: ["professional help", "2 weeks", "daily functioning", "self-harm", "early intervention"],
      category: "clinicalManagement"
    }
  ],

  // Cultural and Contextual (Indian/South Asian)
  culturalContext: [
    {
      question: "How does culture affect mental health?",
      answer: "Culture significantly influences how mental health symptoms are expressed, understood, and treated. In Indian culture, mental health issues might be expressed through physical symptoms, family dynamics play a crucial role, and there may be stigma around seeking help. It's important to find culturally sensitive care that understands your background and values.",
      keywords: ["culture", "Indian culture", "physical symptoms", "family dynamics", "stigma"],
      category: "culturalContext"
    },
    {
      question: "What about family pressure and mental health?",
      answer: "Family expectations and pressure can significantly impact mental health, especially in collectivistic cultures. It's common to feel torn between personal needs and family expectations. Setting healthy boundaries while maintaining family relationships is important. Family therapy can help improve communication and understanding.",
      keywords: ["family pressure", "family expectations", "collectivistic", "boundaries", "family therapy"],
      category: "culturalContext"
    }
  ],

  // Coping Strategies and Self-Help
  copingStrategies: [
    {
      question: "What are grounding techniques?",
      answer: "Grounding techniques help you stay connected to the present moment when feeling overwhelmed or dissociated. Try the 5-4-3-2-1 technique: Name 5 things you can see, 4 you can touch, 3 you can hear, 2 you can smell, 1 you can taste. Or focus on your breath, feeling your feet on the ground, or holding something with texture.",
      keywords: ["grounding", "present moment", "5-4-3-2-1", "breath", "overwhelmed"],
      category: "copingStrategies"
    },
    {
      question: "How can I manage anxiety?",
      answer: "Anxiety management includes deep breathing exercises (4-7-8 breathing: inhale 4 counts, hold 7, exhale 8), progressive muscle relaxation, mindfulness meditation, regular exercise, limiting caffeine, maintaining a sleep schedule, and challenging anxious thoughts. If anxiety is severe or persistent, professional help is recommended.",
      keywords: ["anxiety management", "breathing", "4-7-8", "muscle relaxation", "mindfulness"],
      category: "copingStrategies"
    },
    {
      question: "What helps with depression?",
      answer: "Depression management includes maintaining a routine, getting regular exercise, ensuring adequate sleep, eating nutritious meals, staying connected with supportive people, engaging in activities you once enjoyed (even if you don't feel like it), and challenging negative thought patterns. Professional treatment is often necessary for clinical depression.",
      keywords: ["depression management", "routine", "exercise", "sleep", "social connection"],
      category: "copingStrategies"
    }
  ],

  // Common User Questions and Scenarios
  commonQuestions: [
    {
      question: "I feel like I'm going crazy",
      answer: "Feeling like you're 'going crazy' is actually a common experience during stress, anxiety, or mental health challenges. It often reflects feeling overwhelmed or out of control. This doesn't mean you're actually losing your mind - it's usually a sign that you need support. Consider reaching out to a mental health professional who can help you understand what you're experiencing.",
      keywords: ["going crazy", "overwhelmed", "out of control", "losing mind", "support"],
      category: "commonQuestions"
    },
    {
      question: "I can't stop worrying",
      answer: "Excessive worry is often a sign of anxiety. When worry becomes persistent, uncontrollable, and interferes with daily life, it may indicate an anxiety disorder. Techniques like mindfulness, deep breathing, and challenging anxious thoughts can help. If worry is significantly impacting your life, professional help is recommended.",
      keywords: ["can't stop worrying", "excessive worry", "anxiety", "mindfulness", "breathing"],
      category: "commonQuestions"
    },
    {
      question: "I feel numb and empty",
      answer: "Feeling numb or empty can be a symptom of depression, trauma, or extreme stress. It's your mind's way of protecting you from overwhelming emotions. This feeling is temporary and treatable. Grounding techniques, gentle self-care, and professional support can help you reconnect with your emotions safely.",
      keywords: ["numb", "empty", "depression", "trauma", "stress", "emotions"],
      category: "commonQuestions"
    },
    {
      question: "I have trouble sleeping",
      answer: "Sleep problems are common with mental health conditions like anxiety and depression. Good sleep hygiene includes maintaining a regular schedule, avoiding screens before bed, creating a comfortable environment, and limiting caffeine. If sleep problems persist, they may be a symptom of an underlying condition that needs professional attention.",
      keywords: ["trouble sleeping", "sleep problems", "sleep hygiene", "schedule", "screens"],
      category: "commonQuestions"
    },
    {
      question: "I feel like I'm not myself",
      answer: "Feeling disconnected from yourself can be depersonalization, which is common during stress or trauma. It's like watching yourself from outside your body. This is a protective mechanism and usually temporary. Grounding techniques and professional support can help you feel more connected to yourself again.",
      keywords: ["not myself", "disconnected", "depersonalization", "watching myself", "grounding"],
      category: "commonQuestions"
    }
  ]
};

// Helper function to search training data by keywords
export function searchTrainingData(query: string): any[] {
  const lowerQuery = query.toLowerCase();
  const results: any[] = [];
  
  Object.values(psychiatryTrainingData).forEach(category => {
    category.forEach((item: any) => {
      const keywordMatch = item.keywords.some((keyword: string) => 
        lowerQuery.includes(keyword.toLowerCase())
      );
      
      if (keywordMatch) {
        results.push(item);
      }
    });
  });
  
  return results;
}

// Helper function to get random training examples for a category
export function getRandomTrainingExamples(category: string, count: number = 3): any[] {
  const categoryData = psychiatryTrainingData[category as keyof typeof psychiatryTrainingData];
  if (!categoryData) return [];
  
  const shuffled = [...categoryData].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
}
